const ALL_FEATURE_CARDS_META = { # storypoints, area, counts for debt calc, is start card, effect
	"Card0": [1,"backend", false, false, "unknown"],
	"Card1": [1,"backend", true, false, "unknown"],
	"Card2": [1,"backend", true, false, "unknown"],
	"Card3": [1,"frontend", true, false, "unknown"],
	"Card4": [1,"frontend", true, false, "unknown"],
	"Card5": [1,"frontend", true, false, "unknown"],
	"Card6": [1,"frontend", true, false, "negative"],
	"Card7": [1,"frontend", true, false, "negative"],
	"Card8": [1,"backend", false, false, "positive"],
	"Card9": [1,"frontend", true, false, "positive"],
	"Card10": [2,"backend", true, false, "unknown"],
	"Card11": [2,"frontend", false, true, "unknown"],
	"Card12": [2,"frontend", true, false, "unknown"],
	"Card13": [2,"backend", true, false, "negative"],
	"Card14": [2,"backend", true, false, "positive"],
	"Card15": [2,"backend", false, false, "positive"],
	"Card16": [2,"backend", false, false, "positive"],
	"Card17": [2,"frontend", false, false, "positive"],
	"Card18": [2,"frontend", true, false, "positive"],
	"Card19": [2,"frontend", true, false, "unknown"],
	"Card20": [3,"backend", true, true, "negative"],
	"Card21": [3,"backend", true, false, "negative"],
	"Card22": [3,"backend", true, true, "negative"],
	"Card23": [3,"frontend", true, false, "negative"],
	"Card24": [3,"frontend", true, false, "positive"],
	"Card25": [1,"frontend", true, false, "negative"],
	"Card26": [2,"backend", true, false, "unknown"]
}
const ALL_FEATURE_CARDS_TEXT = {
	"Card0": ["CARD0_FRONT", "CARD0_BACK", "CARD0_EFFECT"],
	"Card1": ["CARD1_FRONT", "CARD1_BACK", "CARD1_EFFECT"],
	"Card2": ["CARD2_FRONT", "CARD2_BACK", "CARD2_EFFECT"],
	"Card3": ["CARD3_FRONT", "CARD3_BACK", "CARD3_EFFECT"],
	"Card4": ["CARD4_FRONT", "CARD4_BACK", "CARD4_EFFECT"],
	"Card5": ["CARD5_FRONT", "CARD5_BACK", "CARD5_EFFECT"],
	"Card6": ["CARD6_FRONT", "CARD6_BACK", "CARD6_EFFECT"],
	"Card7": ["CARD7_FRONT", "CARD7_BACK", "CARD7_EFFECT"],
	"Card8": ["CARD8_FRONT", "CARD8_BACK", "CARD8_EFFECT"],
	"Card9": ["CARD9_FRONT", "CARD9_BACK", "CARD9_EFFECT"],
	"Card10": ["CARD10_FRONT", "CARD10_BACK", "CARD10_EFFECT"],
	"Card11": ["CARD11_FRONT", "CARD11_BACK", "CARD11_EFFECT"],
	"Card12": ["CARD12_FRONT", "CARD12_BACK", "CARD12_EFFECT"],
	"Card13": ["CARD13_FRONT", "CARD13_BACK", "CARD13_EFFECT"],
	"Card14": ["CARD14_FRONT", "CARD14_BACK", "CARD14_EFFECT"],
	"Card15": ["CARD15_FRONT", "CARD15_BACK", "CARD15_EFFECT"],
	"Card16": ["CARD16_FRONT", "CARD16_BACK", "CARD16_EFFECT"],
	"Card17": ["CARD17_FRONT", "CARD17_BACK", "CARD17_EFFECT"],
	"Card18": ["CARD18_FRONT", "CARD18_BACK", "CARD18_EFFECT"],
	"Card19": ["CARD19_FRONT", "CARD19_BACK", "CARD19_EFFECT"],
	"Card20": ["CARD20_FRONT", "CARD20_BACK", "CARD20_EFFECT"],
	"Card21": ["CARD21_FRONT", "CARD21_BACK", "CARD21_EFFECT"],
	"Card22": ["CARD22_FRONT", "CARD22_BACK", "CARD22_EFFECT"],
	"Card23": ["CARD23_FRONT", "CARD23_BACK", "CARD23_EFFECT"],
	"Card24": ["CARD24_FRONT", "CARD24_BACK", "CARD24_EFFECT"],
	"Card25": ["CARD25_FRONT", "CARD25_BACK", "CARD25_EFFECT"],
	"Card26": ["CARD26_FRONT", "CARD26_BACK", "CARD26_EFFECT"],
}

const ALL_FEATURE_CARDS_BACK_META = { 
	"Card0": [["remove_technical_debt",[1, "backend"]]],
	"Card1": [["features", 1]],
	"Card2": [["add_storypoints",[1, 1]]],
	"Card3": [["bugs",2]],
	"Card4": [["new_values",3],["must_choose", 0], ["back_to_backlog", 0]],
	"Card5": [["add_technical_debt",[1, "frontend"]]],
	"Card6": [["features", 1], ["must_choose", 0]],
	"Card7": [["bugs",1]],
	"Card8": [],
	"Card9": [["add_storypoints",[1, 10000]]],
	"Card10": [],
	"Card11": [["remove_storypoints",[1, 1]], ["remove_technical_debt",[1, "frontend"]]],
	"Card12": [["bugs",1]],
	"Card13": [["bugs",1]],
	"Card14": [["add_storypoints",[1, 10000]]],
	"Card15": [],
	"Card16": [["remove_technical_debt",[1, "backend"]]],
	"Card17": [["remove_technical_debt",[1, "frontend"]]],
	"Card18": [["cheap_feature_is_implemented",1]],
	"Card19": [["new_values",1], ["back_to_backlog", 0], ["cannot_be_choosen", 0]],
	"Card20": [["add_technical_debt",[1, "backend"]]],
	"Card21": [["new_values",2], ["back_to_backlog", 0]],
	"Card22": [["features", 1]],
	"Card23": [["bugs",1]],
	"Card24": [["add_storypoints",[1, 10000]]],
	"Card25": [["remove_storypoints",[2, 10000]]],
	"Card26": [["add_technical_debt",[1, "backend"]], ["add_technical_debt",[1, "frontend"]]],
}

const ALL_FEATURE_CARDS = { #front, back
	"frontend": ["res://assets/cards/feat_frontend_front.png","res://assets/cards/back_front.png"],
	"backend": ["res://assets/cards/feat_backend_front.png","res://assets/cards/back_back.png"],
	"positive":["res://assets/cards/positive_effect.png"],
	"negative":["res://assets/cards/negative_effect.png"],
	"unknown":["res://assets/cards/unknown_effect.png"],
	}
